version: '3.7'

services:
  db:
    container_name: "test_db"
    image: 085875424333.dkr.ecr.us-west-2.amazonaws.com/go-docker-mysql-aws:db_1.0
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "test_api"
    image: 085875424333.dkr.ecr.us-west-2.amazonaws.com/go-docker-mysql-aws:api_1.0
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default:
volumes:
  mysql_data:
